FROM ghcr.io/minhuw/base-dev:latest

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get -y install bc bison build-essential cpio flex git pahole libelf-dev libssl-dev liblzma-dev libncurses-dev libzstd-dev wget zstd && rm -rf /var/lib/apt/lists/*