FROM ubuntu:22.04

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get -y install bc bison build-essential cpio flex git libelf-dev libssl-dev wget zstd && rm -rf /var/lib/apt/lists/*