name: Create and publish kernel images

on:
    workflow_dispatch:

    push:
        branches:
          - 'master'
        paths:
          - containers/kernel/**
          - .github/workflows/build_kernel.yaml

env:
    REGISTRY: ghcr.io

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
              include:
                - dockerfile: ./containers/kernel/Dockerfile.ci
                  image: ghcr.io/${{ github.actor }}/kernel-ci
                - dockerfile: ./containers/kernel/Dockerfile.dev
                  image: ghcr.io/${{ github.actor }}/kernel-dev
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: ${{ matrix.image }}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
              with:
                context: .
                file: ${{ matrix.dockerfile }}
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

            - name: Analyze Docker image
              run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --env CI=true wagoodman/dive:latest ${{ steps.meta.outputs.tags }}
